'use client';
import { useEffect, useMemo, useState } from 'react';
import Sidebar from '@/components/sidebar';
import { AppLog, GenerationRecord, ModelChoice, Ratio, Screen, StructuredPrompt } from '@/types/app';
import { storage } from '@/lib/storage';
import { estimate, metrics } from '@/lib/pricing';
import { toStructuredText } from '@/lib/prompt';
import { dt, uid } from '@/lib/utils';

const mapModel=(m:ModelChoice)=>m==='seedance2'?'dreamina-seedance-2-0-260128':'dreamina-seedance-2-0-fast-260128';
export default function Home(){const [screen,setScreen]=useState<Screen>('generate'); const [open,setOpen]=useState(false); const [bp,setBp]=useState(''); const [or,setOr]=useState(''); const [logline,setLogline]=useState(''); const [sp,setSp]=useState<StructuredPrompt>(storage.loadDraft()); const [choice,setChoice]=useState<ModelChoice>('seedance2'); const [duration,setDuration]=useState<4|6>(4); const [ratio,setRatio]=useState<Ratio>('9:16'); const [audio,setAudio]=useState(true); const [busy,setBusy]=useState(false); const [status,setStatus]=useState('Idle'); const [history,setHistory]=useState<GenerationRecord[]>([]); const [logs,setLogs]=useState<AppLog[]>([]); const [usage,setUsage]=useState(storage.loadUsage());
useEffect(()=>{setBp(localStorage.getItem(storage.keys.bp)||''); setOr(localStorage.getItem(storage.keys.or)||''); setHistory(storage.loadHistory()); setLogs(storage.loadLogs());},[]);
useEffect(()=>{localStorage.setItem(storage.keys.draft,JSON.stringify(sp));},[sp]);
const addLog=(l:AppLog)=>{const n=[l,...logs]; setLogs(n); storage.saveLogs(n);};
const saveKeys=()=>{localStorage.setItem(storage.keys.bp,bp); localStorage.setItem(storage.keys.or,or);};
const suggest=async()=>{setBusy(true); setStatus('Requesting Prompt Suggestion...'); const body={apiKey:or,logline}; const r=await fetch('/api/openrouter/suggest-prompt',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}); const j=await r.json(); if(!r.ok) {addLog({id:uid(),timestamp:new Date().toISOString(),actionType:'openrouter',status:'failed',message:'Suggest failed',errorDetails:j.error,rawJson:j}); setStatus('Prompt Suggestion failed'); setBusy(false); return;} setSp(j.structuredPrompt); addLog({id:uid(),timestamp:new Date().toISOString(),actionType:'openrouter',status:'succeeded',message:'Prompt Suggestion complete',rawJson:j}); setStatus('Prompt Suggestion complete'); setBusy(false);};
const runOne=async(model:string)=>{const rec:GenerationRecord={id:uid(),timestamp:new Date().toISOString(),model,duration,ratio,generateAudio:audio,status:'running',logline,structuredPrompt:sp}; setHistory(v=>[rec,...v]); addLog({id:uid(),timestamp:rec.timestamp,actionType:'byteplus.create',status:'running',message:'Creating task',model,rawJson:{model}});
const payload={model,content:[{type:'text',text:toStructuredText(sp)}],generate_audio:audio,ratio,duration,watermark:false,resolution:'480p'};
const cr=await fetch('/api/byteplus/create-task',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({apiKey:bp,payload})}); const cj=await cr.json(); if(!cr.ok){rec.status='failed';rec.error=cj.error; finalize(rec); return;} rec.taskId=cj.id;
const start=Date.now(); while(Date.now()-start<600000){await new Promise(r=>setTimeout(r,5000)); const gr=await fetch('/api/byteplus/get-task',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({apiKey:bp,taskId:rec.taskId})}); const gj=await gr.json(); addLog({id:uid(),timestamp:new Date().toISOString(),actionType:'byteplus.poll',status:gj.status||'unknown',message:'Polling task',model,taskId:rec.taskId,rawJson:gj}); if(gj.status==='succeeded'){rec.status='succeeded'; rec.videoUrl=gj.content?.video_url; rec.usageTotalTokens=gj.usage?.total_tokens??0; rec.usageCompletionTokens=gj.usage?.completion_tokens??0; const tokensUsed=rec.usageTotalTokens ?? 0; rec.estimatedCostUsd=estimate(model,tokensUsed).usd; finalize(rec); return;} if(gj.status==='failed'){rec.status='failed'; rec.error=gj.error?.message||'Generation failed'; finalize(rec); return;} }
rec.status='timeout'; rec.error='Polling timed out'; finalize(rec);
};
const finalize=(rec:GenerationRecord)=>{const n=[rec,...history.filter(h=>h.id!==rec.id)]; setHistory(n); storage.saveHistory(n); const u={...usage,totalVideos:usage.totalVideos+1,successVideos:usage.successVideos+(rec.status==='succeeded'?1:0),failedVideos:usage.failedVideos+(rec.status==='succeeded'?0:1),totalTokens:usage.totalTokens+(rec.usageTotalTokens??0),totalCompletionTokens:usage.totalCompletionTokens+(rec.usageCompletionTokens??0),resourceTokensConsumed:usage.resourceTokensConsumed+(rec.usageTotalTokens??0),usdUsed:usage.usdUsed+(rec.estimatedCostUsd??0)}; setUsage(u); storage.saveUsage(u);};
const generate=async()=>{setBusy(true); setStatus('Generating...'); if(choice==='both'){await runOne('dreamina-seedance-2-0-260128'); await runOne('dreamina-seedance-2-0-fast-260128');} else {await runOne(mapModel(choice));} setStatus('Done'); setBusy(false);};
const m=useMemo(()=>metrics(usage.resourceTokensConsumed,usage.successVideos),[usage]);
return <main className='min-h-screen p-2'><Sidebar open={open} setOpen={setOpen} screen={screen} setScreen={setScreen}/><div className='max-w-3xl mx-auto space-y-3'>
{screen==='settings'&&<section className='card space-y-2'><h2>Settings</h2><input className='input' placeholder='BytePlus API key' value={bp} onChange={e=>setBp(e.target.value)}/><input className='input' placeholder='OpenRouter API key' value={or} onChange={e=>setOr(e.target.value)}/><button className='btn-primary' onClick={saveKeys}>Save Keys</button></section>}
{screen==='generate'&&<section className='card space-y-2'><h2>Generate</h2><textarea className='input min-h-20' placeholder='Logline' value={logline} onChange={e=>setLogline(e.target.value)}/><button className='btn-primary' disabled={!or||busy||!logline} onClick={suggest}>Suggest Seedance Prompt</button>{Object.entries(sp).map(([k,v])=><input key={k} className='input' value={v} onChange={e=>setSp({...sp,[k]:e.target.value})} placeholder={k}/>) }<div className='flex gap-2 flex-wrap'><button className='btn-secondary' onClick={()=>navigator.clipboard.writeText(toStructuredText(sp))}>Copy Structured Prompt</button><button className='btn-secondary' onClick={()=>navigator.clipboard.writeText(JSON.stringify({model:mapModel(choice==='both'?'seedance2':choice),content:[{type:'text',text:toStructuredText(sp)}],generate_audio:audio,ratio,duration,watermark:false,resolution:'480p'},null,2))}>Copy Full BytePlus JSON Payload</button></div><select className='input' value={choice} onChange={e=>setChoice(e.target.value as ModelChoice)}><option value='seedance2'>Seedance 2</option><option value='seedance2fast'>Seedance 2 Fast</option><option value='both'>Generate Both (2 generations)</option></select><div className='flex gap-2'><select className='input' value={duration} onChange={e=>setDuration(Number(e.target.value) as 4|6)}><option value={4}>4 seconds</option><option value={6}>6 seconds</option></select><select className='input' value={ratio} onChange={e=>setRatio(e.target.value as Ratio)}><option>9:16</option><option>16:9</option></select></div><label><input type='checkbox' checked={audio} onChange={e=>setAudio(e.target.checked)}/> generate_audio</label><p>Resolution: 480p</p><button className='btn-primary' disabled={!bp||!or||busy} onClick={generate}>Generate</button><p>{status}</p>{history[0]?.videoUrl&&<video className='w-full rounded' controls src={history[0].videoUrl}/>}</section>}
{screen==='history'&&<section className='card'>{history.map(h=><div key={h.id} className='border-b border-border py-2 text-sm'><div>{dt(h.timestamp)} • {h.model} • {h.status}</div><div>{h.logline}</div>{h.videoUrl&&<a className='text-blue-400' href={h.videoUrl} target='_blank'>Download</a>}</div>)}</section>}
{screen==='usage'&&<section className='card text-sm space-y-1'><div>Total videos: {usage.totalVideos}</div><div>Success: {usage.successVideos}</div><div>Failed: {usage.failedVideos}</div><div>Total BytePlus tokens: {usage.totalTokens}</div><div>Total completion tokens: {usage.totalCompletionTokens}</div><div>Resource tokens consumed: {usage.resourceTokensConsumed}</div><div>Remaining resource-pack tokens: {m.remainingTokens}</div><div>Approx remaining videos: {m.approxVideos??'Not enough data'}</div><div>USD used: ${usage.usdUsed.toFixed(4)}</div><div>USD remaining: ${m.remainingUsd.toFixed(4)}</div></section>}
{screen==='logs'&&<section className='card space-y-2'>{logs.map(l=><details key={l.id} className='text-sm border-b border-border py-1'><summary>{dt(l.timestamp)} • {l.actionType} • {l.status} • {l.message}</summary><pre className='text-xs overflow-auto'>{JSON.stringify(l.rawJson,null,2)}</pre></details>)}</section>}
</div></main>; }
